### ISSUE TITLE
MethodNotFound: Unhandled method workspace/configuration

### ISSUE THREAD

**Issue by davidanthoff** [julia-vscode/LanguageServer.jl#600]
From [crash reporting](https://portal.azure.com/#blade/AppInsightsExtension/DetailsV2Blade/ComponentId/%7B%22Name%22%3A%22julia-vscode%22%2C%22SubscriptionId%22%3A%226803c4ed-bcb4-41d4-bceb-7faf5e7a3469%22%2C%22ResourceGroup%22%3A%22Default%22%7D/DataModel/%7B%22eventId%22%3A%225cf8dec1-688e-11ea-837a-3feac4fb451b%22%2C%22timestamp%22%3A%222020-03-17T20%3A31%3A49.117Z%22%2C%22cacheId%22%3A%22fd2abbd0-8af3-471a-aa7a-050745131602%22%2C%22eventTable%22%3A%22exceptions%22%7D).

Stack trace:
```
LanguageServer.JSONRPCEndpoints.JSONRPCError:
   at send_request(::LanguageServer.JSONRPCEndpoints.JSONRPCEndpoint, ::String, ::LanguageServer.ConfigurationParams) (.\scripts\languageserver\packages\LanguageServer\src\jsonrpcendpoint.jl161)
   at request_julia_config(::LanguageServerInstance) (.\scripts\languageserver\packages\LanguageServer\src\requests\workspace.jl77)
   at process(::LanguageServer.JSONRPC.Request{Val{:initialized},Dict{String,Any}}, ::LanguageServerInstance) (.\scripts\languageserver\packages\LanguageServer\src\requests\init.jl159)
   at run(::LanguageServerInstance) (.\scripts\languageserver\packages\LanguageServer\src\languageserverinstance.jl233)
   at top-level scope (.\scripts\languageserver\main.jl28)
   at include (boot.jl328)
   at include_relative(::Module, ::String) (loading.jl1105)
   at include(::Module, ::String) (Base.jl31)
   at exec_options(::Base.JLOptions) (client.jl287)
   at _start() (client.jl460)
```

I think we need to rework how we load configuration in general and follow the examples from the docs.

**Comment by non-Jedi** [comment]
Do you not get an event log in crash reports showing client and server requests leading up to the crash? Very difficult to debug otherwise. Looking at the code, this looks like a client-side problem rather than server-side since the response has an `error` key with empty `code` and `message`.

**Comment by davidanthoff** [comment]
Unfortunately we don't... I'll look into sending more log info in crash reports, but not sure we can easily do that...

**Comment by ZacLN** [comment]
Is this likely to have been fixed by the change to how we handle configurations?

**Comment by davidanthoff** [comment]
I had hoped so, but we are still getting crash reports from this... So, no.

**Comment by ZacLN** [comment]
Erg. I'm still feeling really lost on this. Do we need to check and store [this](https://github.com/julia-vscode/LanguageServer.jl/blob/master/src/protocol/initialize.jl#L36) before sending requests to the client?

**Comment by non-Jedi** [comment]
The only thing I see in the `workspace/configuration` request that's out of spec is that it sends `"scopeUri": nil` when [scopeUri is required to be a DocumentUri](https://microsoft.github.io/language-server-protocol/specifications/specification-current/#workspace_configuration) which is an alias for string. Instead, scopeUri can simply be omitted.

Could be worth fixing that just in case its the problem?

**Comment by davidanthoff** [comment]
So maybe we wait and see whether #665 fixes this, and whether #662 gives us more info, right?

**Comment by davidanthoff** [comment]
We're STILL seeing this in the latest version of the extension that I published today :( This is honestly driving me nuts, I have no more ideas what might be going wrong here...

**Comment by ZacLN** [comment]
As per my comment above: https://github.com/julia-vscode/LanguageServer.jl/pull/693 seems worth a try
