### ISSUE TITLE
Support for Julia v1.6 "import X as Y" syntax

### ISSUE THREAD

**Issue by ashiklom** [julia-vscode/LanguageServer.jl#925]
As of Julia v1.6, the following is valid syntax:

```julia
import DataFrames as DF
```

Indeed, it works exactly as expected in a Julia REPL.

However, when typing this code into Emacs (using the `lsp-julia` package, a thin wrapper around `LanguageServer.jl`), LanguageServer calls this a `Parsing error [Julia]` and also throws a warning for `Missing reference: DF [Julia]`. Also, less important, but completion on `DF.|` (where `|` is the cursor) doesn't return any candidates (whereas `import DataFrames` followed by completion on `DataFrames.|` works great!).

Not sure if this is something with my configuration or a problem with LanguageServer itself.

**Comment by pfitzseb** [comment]
This should be fixed on CSTParser#master already. Can you try updating to that? We'll tag a new release soonish, I think.

**Comment by ashiklom** [comment]
Thanks for the quick reply! Confirming that switching to `LanguageServer#master` and `CSTParser#master` no longer throws a Parsing error. 

However, `import Statistics as ST` does still throw two warnings: `Missing reference: Statistics` and `Missing reference: ST`. Completion for the `ST` variable also doesn't work (though that may be a separate issue). 

The most pressing issue about the parsing error has been resolved, so this can probably be closed, but I figured I'd mention the remaining issues for reference.
